name: Hello            

on:                        
  push:
    branches:
      - dev                   

jobs:                      
  hello:                   
    runs-on: ubuntu-latest 

    steps:                 
      - run: echo "Hello World"  